name: ci

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: "20"
            cache: "npm"
            cache-dependency-path: package-lock.json
        - name: Install dependencies
          run: npm install
        - name: Execute test cases
          run: npm run test
        - name: Build
          run: npm run build